development:
  secret_key_base: 39e864f0e09792ee88d29784bcf54071cc07a4f4242cb50740dbcd1db1ce9e77d4ed09e7020eeefd9295a5282413e71549b3864f3cc92303a8ae9e55ebff8fff
  FACEBOOK_APP_ID: 104838946526158
  FACEBOOK_SECRET: 9a2be1312d35f6e97663c3ebaa89243d

test:
  secret_key_base: 5872efe1599a82ac90e7f3c6ae5cab845dab8af8e5bac121a713b05ae6d0ca17782511fc7352f152cdd2022d87b3ba082a0f6d572b8e9e70fc3740d0ac411d85
  FACEBOOK_APP_ID: 104838946526158
  FACEBOOK_SECRET: 9a2be1312d35f6e97663c3ebaa89243d

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
